fix: handle error on runner again

diff --git a/.github/workflows/auto.yml b/.github/workflows/auto.yml
--- a/.github/workflows/auto.yml
+++ b/.github/workflows/auto.yml
@@ -2,7 +2,7 @@ name: Automated Daily Commit with Emojis
 
 on:
   schedule:
-    - cron: '*/1 * * * *' # Runs every minute for demonstration; adjust as needed
+    - cron: '*/1 * * * *' # Adjust this as needed
   workflow_dispatch:
 
 permissions:
@@ -14,11 +14,10 @@ jobs:
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v3
-        with:
-          fetch-depth: 0  # Fetch all history for all tags and branches
 
       - name: Update Log File
-        run: echo "Update made at $(date '+%Y-%m-%d %H:%M:%S')" > update_logs.txt
+        run: |
+          echo "Update made at $(date '+%Y-%m-%d %H:%M:%S')" > update_logs.txt
 
       - name: Configure Git
         run: |
@@ -28,14 +27,14 @@ jobs:
       - name: Commit and Push Changes If Any
         run: |
           emojis=("🎉" "🚀" "✨" "🔥" "🌈" "💥" "🍀" "🚀" "💫" "🎈")
-          emoji_index=$(($RANDOM % ${#emojis[@]}))
+          emoji_index=$((RANDOM % 10))
           selected_emoji=${emojis[$emoji_index]}
           commit_message="Enhanced daily update: $(date '+%Y-%m-%d %H:%M:%S') $selected_emoji"
 
-          if [ -z "$(git status --porcelain)" ]; then
+          if [[ -z $(git status --porcelain) ]]; then
             echo "No changes to commit."
           else
-            git pull --rebase  # Ensure the local branch is up-to-date with remote
+            git pull --rebase || echo "Rebase not required"
             git add -A
-            git commit -m "${commit_message}"
+            git commit -m "$commit_message"
             git push
